In [1]:
import pandas as pd 
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
from nltk.util import ngrams 
porter = nltk.PorterStemmer()
from nltk.stem import WordNetLemmatizer
wordNet_lemmetizer = WordNetLemmatizer()
from nltk.util import ngrams 
from collections import Counter

In [2]:
df = pd.read_csv('Context.csv')
df

Text  Context/Topic
0                  The eternal mystique of Goldman Sachs       Politics
1      Either you don't care enough to actually tell ...           Love
2                                    I am such an IDIOT.  Heavy Emotion
3      While lifting weights on Friday and doing bent...         Health
4                                Something's watching me        Animals
...                                                  ...            ...
31381                                          **TL;DR**  Heavy Emotion
31382                               Looks are everything  Heavy Emotion
31383  Teacher: write a thing that you want to do til...      Education
31384  General Secretary of India's ruling party, the...       Politics
31385  Heastie rewarded contributors, racked up unusu...       Politics

[31386 rows x 2 columns]

In [3]:
df = df.rename(columns={'Text':'Text','Context/Topic':'label'})
df.head() 

Text          label
0              The eternal mystique of Goldman Sachs       Politics
1  Either you don't care enough to actually tell ...           Love
2                                I am such an IDIOT.  Heavy Emotion
3  While lifting weights on Friday and doing bent...         Health
4                            Something's watching me        Animals

In [4]:
#check forr null values 

In [5]:
df.isnull().sum()

Text     0
label    0
dtype: int64

In [6]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]','',text)
    txt = []
    for w in text.split():
        stemWord = porter.stem(w)
        txt.append(stemWord)
    txt = ' '.join(txt)    
    return txt

In [32]:
#clean text 
df['Text'] = df['Text'].apply(clean_text)
df.head() 

Text          label
0                  the etern mystiqu of goldman sach       Politics
1  either you dont care enough to actual tell me ...           Love
2                                 i am such an idiot  Heavy Emotion
3  while lift weight on friday and do bent over r...         Health
4                                    someth watch me        Animals

In [8]:
#N-Gram
TopicL = list(df['Text'])
TopicL #segmentation
list1=[]
list1.extend(TopicL[0:100])
S = ' '.join(list1)
S

# punkt = nltk.data.load(r'./tokenizers/punkt/english.pickle')
# t = punkt.tokenize(S) 
# t 

'the etern mystiqu of goldman sach either you dont care enough to actual tell me how u feel and i am a dumbass think we could get again work on thi or i am complet fuck in the head becaus of all your mind game shit over the year to where i say thing and do thing becaus i know what you use to say or what you use to think and i am all over the place tryi g to be sure how not to upset u or make you think i am some low life and pathet i am such an idiot while lift weight on friday and do bent over row i felt a sharp pain in my lower back some would say i threw it out and i had thi happen one other time about 6 month ago drop to my knee and wa sore for the rest of the day overnight it just becam terribl everi time my bodi want to move i woke everybodi in the room up with moan of pain wife dog cat someth watch me plantação de palma na indonésia é uma dura realidad para os orangotango the milki way project probe star format with first result on yellowbal from dr2 the pinnacl of american finan

In [9]:
Tokinize=nltk.word_tokenize(S) #tokenization 
Tokinize

['the',
 'etern',
 'mystiqu',
 'of',
 'goldman',
 'sach',
 'either',
 'you',
 'dont',
 'care',
 'enough',
 'to',
 'actual',
 'tell',
 'me',
 'how',
 'u',
 'feel',
 'and',
 'i',
 'am',
 'a',
 'dumbass',
 'think',
 'we',
 'could',
 'get',
 'again',
 'work',
 'on',
 'thi',
 'or',
 'i',
 'am',
 'complet',
 'fuck',
 'in',
 'the',
 'head',
 'becaus',
 'of',
 'all',
 'your',
 'mind',
 'game',
 'shit',
 'over',
 'the',
 'year',
 'to',
 'where',
 'i',
 'say',
 'thing',
 'and',
 'do',
 'thing',
 'becaus',
 'i',
 'know',
 'what',
 'you',
 'use',
 'to',
 'say',
 'or',
 'what',
 'you',
 'use',
 'to',
 'think',
 'and',
 'i',
 'am',
 'all',
 'over',
 'the',
 'place',
 'tryi',
 'g',
 'to',
 'be',
 'sure',
 'how',
 'not',
 'to',
 'upset',
 'u',
 'or',
 'make',
 'you',
 'think',
 'i',
 'am',
 'some',
 'low',
 'life',
 'and',
 'pathet',
 'i',
 'am',
 'such',
 'an',
 'idiot',
 'while',
 'lift',
 'weight',
 'on',
 'friday',
 'and',
 'do',
 'bent',
 'over',
 'row',
 'i',
 'felt',
 'a',
 'sharp',
 'pain',
 '

In [10]:
from nltk.corpus import stopwords
stop_list = stopwords.words('english')
filter_words = [] 
for word in Tokinize:
    if word not in stop_list:
        filter_words.append(word)
filter_words        #stopwords

['etern',
 'mystiqu',
 'goldman',
 'sach',
 'either',
 'dont',
 'care',
 'enough',
 'actual',
 'tell',
 'u',
 'feel',
 'dumbass',
 'think',
 'could',
 'get',
 'work',
 'thi',
 'complet',
 'fuck',
 'head',
 'becaus',
 'mind',
 'game',
 'shit',
 'year',
 'say',
 'thing',
 'thing',
 'becaus',
 'know',
 'use',
 'say',
 'use',
 'think',
 'place',
 'tryi',
 'g',
 'sure',
 'upset',
 'u',
 'make',
 'think',
 'low',
 'life',
 'pathet',
 'idiot',
 'lift',
 'weight',
 'friday',
 'bent',
 'row',
 'felt',
 'sharp',
 'pain',
 'lower',
 'back',
 'would',
 'say',
 'threw',
 'thi',
 'happen',
 'one',
 'time',
 '6',
 'month',
 'ago',
 'drop',
 'knee',
 'wa',
 'sore',
 'rest',
 'day',
 'overnight',
 'becam',
 'terribl',
 'everi',
 'time',
 'bodi',
 'want',
 'move',
 'woke',
 'everybodi',
 'room',
 'moan',
 'pain',
 'wife',
 'dog',
 'cat',
 'someth',
 'watch',
 'plantação',
 'de',
 'palma',
 'na',
 'indonésia',
 'é',
 'uma',
 'dura',
 'realidad',
 'para',
 'os',
 'orangotango',
 'milki',
 'way',
 'project

In [11]:
import string
pn = string.punctuation
filter_text = []
pn_list = list(pn)
for char in S:
    if char not in pn_list:
        filter_text.append(char)
filter_text = ''.join(filter_text)
filter_text
filtter = filter_text.split() 
filtter
#nltk.word_tokenize(filter_text)
#punctuation

['the',
 'etern',
 'mystiqu',
 'of',
 'goldman',
 'sach',
 'either',
 'you',
 'dont',
 'care',
 'enough',
 'to',
 'actual',
 'tell',
 'me',
 'how',
 'u',
 'feel',
 'and',
 'i',
 'am',
 'a',
 'dumbass',
 'think',
 'we',
 'could',
 'get',
 'again',
 'work',
 'on',
 'thi',
 'or',
 'i',
 'am',
 'complet',
 'fuck',
 'in',
 'the',
 'head',
 'becaus',
 'of',
 'all',
 'your',
 'mind',
 'game',
 'shit',
 'over',
 'the',
 'year',
 'to',
 'where',
 'i',
 'say',
 'thing',
 'and',
 'do',
 'thing',
 'becaus',
 'i',
 'know',
 'what',
 'you',
 'use',
 'to',
 'say',
 'or',
 'what',
 'you',
 'use',
 'to',
 'think',
 'and',
 'i',
 'am',
 'all',
 'over',
 'the',
 'place',
 'tryi',
 'g',
 'to',
 'be',
 'sure',
 'how',
 'not',
 'to',
 'upset',
 'u',
 'or',
 'make',
 'you',
 'think',
 'i',
 'am',
 'some',
 'low',
 'life',
 'and',
 'pathet',
 'i',
 'am',
 'such',
 'an',
 'idiot',
 'while',
 'lift',
 'weight',
 'on',
 'friday',
 'and',
 'do',
 'bent',
 'over',
 'row',
 'i',
 'felt',
 'a',
 'sharp',
 'pain',
 '

In [12]:
#Apply n_gram

In [13]:
def extract_gram(filtter,num):
        filtter  = " ".join(filtter)
        n_grams = ngrams(nltk.word_tokenize(filtter), num)
        return [" ".join(grams) for grams in n_grams]
#print("1-gram :" , extract_gram(filtter , 1))   
print("2-gram :" , extract_gram(filtter , 2))   
#print("3-gram :" , extract_gram(filtter , 3))   
#print("4-gram :" , extract_gram(filtter ,4))     

2-gram : ['the etern', 'etern mystiqu', 'mystiqu of', 'of goldman', 'goldman sach', 'sach either', 'either you', 'you dont', 'dont care', 'care enough', 'enough to', 'to actual', 'actual tell', 'tell me', 'me how', 'how u', 'u feel', 'feel and', 'and i', 'i am', 'am a', 'a dumbass', 'dumbass think', 'think we', 'we could', 'could get', 'get again', 'again work', 'work on', 'on thi', 'thi or', 'or i', 'i am', 'am complet', 'complet fuck', 'fuck in', 'in the', 'the head', 'head becaus', 'becaus of', 'of all', 'all your', 'your mind', 'mind game', 'game shit', 'shit over', 'over the', 'the year', 'year to', 'to where', 'where i', 'i say', 'say thing', 'thing and', 'and do', 'do thing', 'thing becaus', 'becaus i', 'i know', 'know what', 'what you', 'you use', 'use to', 'to say', 'say or', 'or what', 'what you', 'you use', 'use to', 'to think', 'think and', 'and i', 'i am', 'am all', 'all over', 'over the', 'the place', 'place tryi', 'tryi g', 'g to', 'to be', 'be sure', 'sure how', 'how no

In [14]:
def Count(text):
    fd =nltk.FreqDist(text)
    return fd

In [15]:
biGramCount = Count(extract_gram(filtter  , 2))
uniGramCount = Count(extract_gram(filtter  , 1))
#biGramCount
#uniGramCount

In [16]:
for k,v in biGramCount.items():
    t = k.split()
    countUnigram = uniGramCount[t[0]]
    p = v / countUnigram
    print(f'P({k}|{t[0]}) = {p}')

P(the etern|the) = 0.008
P(etern mystiqu|etern) = 1.0
P(mystiqu of|mystiqu) = 1.0
P(of goldman|of) = 0.0196078431372549
P(goldman sach|goldman) = 1.0
P(sach either|sach) = 1.0
P(either you|either) = 1.0
P(you dont|you) = 0.02
P(dont care|dont) = 0.16666666666666666
P(care enough|care) = 0.3333333333333333
P(enough to|enough) = 0.3333333333333333
P(to actual|to) = 0.01020408163265306
P(actual tell|actual) = 0.5
P(tell me|tell) = 0.2857142857142857
P(me how|me) = 0.03333333333333333
P(how u|how) = 0.047619047619047616
P(u feel|u) = 0.5
P(feel and|feel) = 0.5
P(and i|and) = 0.13253012048192772
P(i am|i) = 0.07207207207207207
P(am a|am) = 0.08333333333333333
P(a dumbass|a) = 0.01694915254237288
P(dumbass think|dumbass) = 1.0
P(think we|think) = 0.16666666666666666
P(we could|we) = 0.05263157894736842
P(could get|could) = 0.4
P(get again|get) = 0.07142857142857142
P(again work|again) = 0.3333333333333333
P(work on|work) = 0.14285714285714285
P(on thi|on) = 0.045454545454545456
P(thi or|thi)

P(i call|i) = 0.009009009009009009
P(call an|call) = 0.25
P(an ambul|an) = 0.1
P(ambul he|ambul) = 1.0
P(is fine|is) = 0.02702702702702703
P(fine now|fine) = 1.0
P(now btw|now) = 0.14285714285714285
P(btw just|btw) = 0.5
P(just need|just) = 0.06666666666666667
P(need a|need) = 0.16666666666666666
P(a few|a) = 0.01694915254237288
P(few week|few) = 0.5
P(week heal|week) = 0.25
P(heal mypet|heal) = 1.0
P(mypet video|mypet) = 1.0
P(video anim|video) = 0.5
P(anim the|anim) = 0.3333333333333333
P(most demand|most) = 0.25
P(demand bird|demand) = 1.0
P(bird ever|bird) = 1.0
P(ever how|ever) = 0.5
P(how can|how) = 0.047619047619047616
P(can i|can) = 0.1
P(i get|i) = 0.009009009009009009
P(get an|get) = 0.07142857142857142
P(an asian|an) = 0.1
P(asian girlfriend|asian) = 1.0
P(girlfriend that|girlfriend) = 1.0
P(that it|that) = 0.05714285714285714
P(it actual|it) = 0.02564102564102564
P(actual trust|actual) = 0.5
P(trust nice|trust) = 1.0
P(nice i|nice) = 0.5
P(i didnt|i) = 0.02702702702702703
P

P(thi just|thi) = 0.05
P(just tast|just) = 0.06666666666666667
P(tast like|tast) = 1.0
P(like shit|like) = 0.125
P(shit the|shit) = 0.25
P(server respond|server) = 0.14285714285714285
P(respond take|respond) = 1.0
P(take shorter|take) = 0.2
P(shorter lick|shorter) = 1.0
P(lick what|lick) = 0.5
P(what concert|what) = 0.07142857142857142
P(concert cost|concert) = 1.0
P(cost 45|cost) = 0.5
P(45 cent|45) = 1.0
P(cent 50|cent) = 0.5
P(50 cent|50) = 1.0
P(cent feat|cent) = 0.5
P(feat nickelback|feat) = 1.0
P(nickelback how|nickelback) = 1.0
P(how is|how) = 0.047619047619047616
P(is duct|is) = 0.02702702702702703
P(duct tape|duct) = 1.0
P(tape like|tape) = 1.0
P(like the|like) = 0.125
P(the forc|the) = 0.008
P(forc it|forc) = 1.0
P(ha a|ha) = 0.14285714285714285
P(a dark|a) = 0.01694915254237288
P(dark side|dark) = 1.0
P(side a|side) = 0.5
P(a light|a) = 0.01694915254237288
P(light side|light) = 1.0
P(side and|side) = 0.5
P(it bind|it) = 0.02564102564102564
P(bind the|bind) = 1.0
P(the galaxi

In [17]:
#feature Extraction

In [18]:
#1Binary
from sklearn.feature_extraction.text import CountVectorizer 
vecc = CountVectorizer(binary=True)
featureBinary = vecc.fit_transform(df['Text'])
pd.DataFrame(featureBinary.toarray() , columns = (vecc.vocabulary_.keys()))

the  etern  mystiqu  of  goldman  sach  either  you  dont  care  ...  \
0        0      0        0   0        0     0       0    0     0     0  ...   
1        0      0        0   0        0     0       0    0     0     0  ...   
2        0      0        0   0        0     0       0    0     0     0  ...   
3        0      0        0   0        0     0       0    0     0     0  ...   
4        0      0        0   0        0     0       0    0     0     0  ...   
...    ...    ...      ...  ..      ...   ...     ...  ...   ...   ...  ...   
31381    0      0        0   0        0     0       0    0     0     0  ...   
31382    0      0        0   0        0     0       0    0     0     0  ...   
31383    0      0        0   0        0     0       0    0     0     0  ...   
31384    0      0        0   0        0     0       0    0     0     0  ...   
31385    0      0        0   0        0     0       0    0     0     0  ...   

       goldenmens_health  pearson  selflearn  strokinoff  rincoln  contirent  \
0                      0        0          0           0        0          0   
1                      0        0          0           0        0          0   
2                      0        0          0           0        0          0   
3                      0        0          0           0        0          0   
4                      0        0          0           0        0          0   
...                  ...      ...        ...         ...      ...        ...   
31381                  0        0          0           0        0          0   
31382                  0        0          0           0        0          0   
31383                  0        0          0           0        0          0   
31384                  0        0          0           0        0          0   
31385                  0        0          0           0        0          0   

       tint  n1039  bjp  heasti  
0         0      0    0       0  
1         0      0    0       0  
2         0      0    0       0  
3         0      0    0       0  
4         0      0    0       0  
...     ...    ...  ...     ...  
31381     0      0    0       0  
31382     0      0    0       0  
31383     0      0    0       0  
31384     0      0    0       0  
31385     0      0    0       0  

[31386 rows x 28116 columns]

In [19]:
#1) Counting
from sklearn.feature_extraction.text import CountVectorizer 
vecc = CountVectorizer(binary=False)
featureCounting = vecc.fit_transform(df['Text'])
pd.DataFrame(featureCounting.toarray() , columns = (vecc.vocabulary_.keys()))

the  etern  mystiqu  of  goldman  sach  either  you  dont  care  ...  \
0        0      0        0   0        0     0       0    0     0     0  ...   
1        0      0        0   0        0     0       0    0     0     0  ...   
2        0      0        0   0        0     0       0    0     0     0  ...   
3        0      0        0   0        0     0       0    0     0     0  ...   
4        0      0        0   0        0     0       0    0     0     0  ...   
...    ...    ...      ...  ..      ...   ...     ...  ...   ...   ...  ...   
31381    0      0        0   0        0     0       0    0     0     0  ...   
31382    0      0        0   0        0     0       0    0     0     0  ...   
31383    0      0        0   0        0     0       0    0     0     0  ...   
31384    0      0        0   0        0     0       0    0     0     0  ...   
31385    0      0        0   0        0     0       0    0     0     0  ...   

       goldenmens_health  pearson  selflearn  strokinoff  rincoln  contirent  \
0                      0        0          0           0        0          0   
1                      0        0          0           0        0          0   
2                      0        0          0           0        0          0   
3                      0        0          0           0        0          0   
4                      0        0          0           0        0          0   
...                  ...      ...        ...         ...      ...        ...   
31381                  0        0          0           0        0          0   
31382                  0        0          0           0        0          0   
31383                  0        0          0           0        0          0   
31384                  0        0          0           0        0          0   
31385                  0        0          0           0        0          0   

       tint  n1039  bjp  heasti  
0         0      0    0       0  
1         0      0    0       0  
2         0      0    0       0  
3         0      0    0       0  
4         0      0    0       0  
...     ...    ...  ...     ...  
31381     0      0    0       0  
31382     0      0    0       0  
31383     0      0    0       0  
31384     0      0    0       0  
31385     0      0    0       0  

[31386 rows x 28116 columns]

In [20]:
#3) TF-IDF

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer 
tf_vec = TfidfVectorizer()
featureTFIDF = tf_vec.fit_transform(df['Text'])
pd.DataFrame(featureTFIDF.toarray() , columns = (tf_vec.vocabulary_.keys()))

the  etern  mystiqu   of  goldman  sach  either  you  dont  care  ...  \
0      0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
1      0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
2      0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
3      0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
4      0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
...    ...    ...      ...  ...      ...   ...     ...  ...   ...   ...  ...   
31381  0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
31382  0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
31383  0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
31384  0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   
31385  0.0    0.0      0.0  0.0      0.0   0.0     0.0  0.0   0.0   0.0  ...   

       goldenmens_health  pearson  selflearn  strokinoff  rincoln  contirent  \
0                    0.0      0.0        0.0         0.0      0.0        0.0   
1                    0.0      0.0        0.0         0.0      0.0        0.0   
2                    0.0      0.0        0.0         0.0      0.0        0.0   
3                    0.0      0.0        0.0         0.0      0.0        0.0   
4                    0.0      0.0        0.0         0.0      0.0        0.0   
...                  ...      ...        ...         ...      ...        ...   
31381                0.0      0.0        0.0         0.0      0.0        0.0   
31382                0.0      0.0        0.0         0.0      0.0        0.0   
31383                0.0      0.0        0.0         0.0      0.0        0.0   
31384                0.0      0.0        0.0         0.0      0.0        0.0   
31385                0.0      0.0        0.0         0.0      0.0        0.0   

       tint  n1039  bjp  heasti  
0       0.0    0.0  0.0     0.0  
1       0.0    0.0  0.0     0.0  
2       0.0    0.0  0.0     0.0  
3       0.0    0.0  0.0     0.0  
4       0.0    0.0  0.0     0.0  
...     ...    ...  ...     ...  
31381   0.0    0.0  0.0     0.0  
31382   0.0    0.0  0.0     0.0  
31383   0.0    0.0  0.0     0.0  
31384   0.0    0.0  0.0     0.0  
31385   0.0    0.0  0.0     0.0  

[31386 rows x 28116 columns]

In [22]:
#Train by Counting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(featureCounting,df['label'],test_size=0.2)

In [23]:
print(x_train.shape)
print(x_test.shape)

(25108, 28116)
(6278, 28116)


In [24]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(x_train,y_train)
print(model.fit(x_train,y_train))

MultinomialNB()


In [25]:
import numpy as np
predicted = model.predict(x_test)
print(np.mean(predicted==y_test)) 

0.5984389933099713


In [26]:
#Train by Binary Encoding
x_train,x_test,y_train,y_test=train_test_split(featureBinary,df['label'],test_size=0.2)
model= MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [27]:
predicted=model.predict(x_test)
print(np.mean(predicted==y_test))

0.6161197833705001


In [28]:
#Train by TFIDF
x_train,x_test,y_train,y_test=train_test_split(featureTFIDF,df['label'],test_size=0.2)
model= MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [29]:
predicted=model.predict(x_test)
print(np.mean(predicted==y_test))

0.5673781459063396


In [30]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test ,predicted))

[[283  12   2  10 108  14  34   4  34  14  16]
 [  1 355   3   0 169   3  42   0  13   2   6]
 [  2   9 222   9 167   5  20   4  47   5  22]
 [ 10  14  14 253 133   8  19  11  19  37  25]
 [  3  12   3   1 621   5  46   4  12   0  16]
 [  0   8   2   0 192 224  51   1  14   0   7]
 [  1   7   2   0 208   5 407   1  13   1   7]
 [  5   3  11   7  67   7  12 293  41   7  12]
 [  8  11   2   1 114   7  33   8 509   3  12]
 [ 14  14  23  57  56   5  17   5  69 154  23]
 [  3   7  11   3 261   6  35   5  37   5 241]]
